---
title: "R Notebook"
output: html_notebook
---
```{r}
install.packages("shinythemes")
install.packages("shiny")
install.packages("leaflet")
install.packages("leaflet.extras")
install.packages("geojsonio")
install.packages("plotly")
install.packages("RColorBrewer")
install.packages("viridis")
install.packages("reshape2")
install.packages("rasterVis")
install.packages("sjPlot")
install.packages("rgdal")
install.packages("ggmap")
install.packages("viridis")

```

```{r}
#eval=FALSE will not run 
#include=FALSE will not show on website
library(sf)          # classes and functions for vector data
library(raster)      # classes and functions for raster data
library(spData)        # load geographic data
library(dplyr)
library(stringr) # for working with strings (pattern matching)
library(spDataLarge)   # load larger geographic data
library(stplanr)      # geographic transport data package
library(tmap)    
```

```{r}
library(shinythemes)
library(shiny)
library(leaflet)
library(leaflet.extras)
library(geojsonio)
library(plotly)
library(RColorBrewer)
library(viridis)
library(ggplot2)
library(reshape2)
library(raster)
library(rasterVis)
library(sjPlot)
library(rgdal)
library(ggmap)
library(viridis)
library(sf)
```
#Load Census Data "TractPolygonCompressed.json"
```{r}
CT <- geojsonio::geojson_read("Data/TractPolygonsCompressed.json", what="sp")
#head(CT)

# subselect Montreal Area
#CT <- CT[CT@data$CMANAME == "Montreal",]
save(CT, file= "Data/CT.Rdata")
```

```{r}
zones_data <- geojsonio::geojson_read("Data/TractTractLinesCompressed.json", what="sp")
save(zones_data,file="Data/zones_data.Rdata")
zones_data[1:10,]
CT[1:10,]
```

```{r}
load("Data/zones_data.Rdata")
load("Data/CT.Rdata")

```

```{r}
install.packages("h5")
library(h5)
dater <- h5file(name='Sus_data.h5','a')
list.datasets(dater,recursive = TRUE)
```
```{r}
dater["testgroup/testset"] <- matrix(1:9,nrow=3)
dater["testgroup/testset2"] <- matrix(1:33,nrow=3)

```

```{r}
dater['testgroup']
h5unlink(dater,"testgroup/CT") #delete dataframe
```

```{r}
CTdata <- load("Data/CT.Rdata")
CT[1:10,]
zones <- load("Data/zones_data.Rdata")
zones_data[1:10,]
dater["testgroup/CT"] <- CTdata
dater["testgroup/zones"] <- zones
dater["testgroup/CT2"] <- CT
desire_rail = top_n(desire_lines, n = 3, wt = train)

class(zones_data)
```

