---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

# Header 1
```{r}
library(sf)
a <- 5
b <- 10
plot(a)
```
# Load packages
```{r}
library(sf)          # classes and functions for vector data
library(raster)      # classes and functions for raster data
library(spData)        # load geographic data
library(dplyr)
library(stringr) # for working with strings (pattern matching)
library(spDataLarge)   # load larger geographic data
library(stplanr)      # geographic transport data package
library(tmap)     
```
# 12.3 Transport Zones
```{r}
data(bristol_zones)
names(bristol_zones)
data(bristol_od) #travel data
bristol_od[1:10,]
names(bristol_od)

zones_attr = bristol_od %>% 
  group_by(o) %>% 
  summarize_if(is.numeric, sum) %>% #the total number of people living in each zone
  dplyr::rename(geo_code = o)

zones_joined = left_join(bristol_zones, zones_attr, by = "geo_code")

zones_od = bristol_od %>% 
  group_by(d) %>% 
  summarize_if(is.numeric, sum) %>% 
  dplyr::select(geo_code = d, all_dest = all) %>% 
  inner_join(zones_joined, ., by = "geo_code")

qtm(zones_od, c("all", "all_dest")) +
  tm_layout(panel.labels = c("Origin", "Destination"))

```
# 12.4 Desire Lines
```{r}
od_top5 = bristol_od %>% 
  arrange(desc(all)) %>% 
  top_n(5, wt = all)

bristol_od$Active = (bristol_od$bicycle + bristol_od$foot) / bristol_od$all * 100

od_intra1 = filter(bristol_od, o == d) #travel within the same zone
od_inter1 = filter(bristol_od, o != d) #between zones
desire_lines1 = od2line(od_inter1, zones_od)
#> Creating centroids representing desire line start and end points.
qtm(desire_lines1, lines.lwd = "all")
```
# 12.5 Routes
```{r}
desire_lines1$distance = as.numeric(st_length(desire_lines1))
desire_carshort1 = dplyr::filter(desire_lines1, car_driver > 300 & distance < 5000)

route_carshort1 = line2route(desire_carshort1, route_fun = route_osrm)
desire_carshort$geom_car = st_geometry(route_carshort1)
mytoken <- readLines("~/Dropbox/dotfiles/cyclestreets-api-key-rl") 
Sys.setenv(CYCLESTREET = "4f8888f9c99f438b")

cycle <-  line2route(desire_carshort1, route_fun = route_cyclestreet)

from <- c(-1.55, 53.80) # geo_code("leeds")
to <- c(-1.76, 53.80) # geo_code("bradford uk")
r <- route_osrm(from, to)
plot(r)

```
# 12.6 Nodes
```{r}
desire_rail = top_n(desire_lines, n = 3, wt = train)

ncol(desire_rail)
#> [1] 10
desire_rail = line_via(desire_rail, bristol_stations) #matrix creation (of origins, destinations and the 'via' points representing rail stations), identification of nearest neighbors and conversion to multilines.
ncol(desire_rail)
#> [1] 13
```

# 12.7 Route networks
```{r}
summary(bristol_ways)

ways_freeway = bristol_ways %>% filter(maxspeed == "70 mph") 
ways_sln = SpatialLinesNetwork(ways_freeway)#represent route networks simultaneously as graphs and a set of geographic lines
slotNames(ways_sln)
#> [1] "sl"          "g"           "nb"          "weightfield"
weightfield(ways_sln)
#> [1] "length"
class(ways_sln@g)

e = igraph::edge_betweenness(ways_sln@g) #the number of shortest paths passing through each edge
plot(ways_sln@sl$geometry, lwd = e / 500)
```
# 12.8 Prioritizing New infrastructure
```{r}
route_rail = desire_rail %>% 
  st_set_geometry("leg_orig") %>% 
  line2route(route_fun = route_osrm) %>% 
  st_set_crs(4326)

route_cycleway = rbind(route_rail, route_carshort)
route_cycleway$all = c(desire_rail$all, desire_carshort$all)

qtm(route_cycleway, lines.lwd = "all")
```

